### PR TITLE
Feather DVI peripheral fix

### PR DESCRIPTION
**Pull request by ladyada**
Fix SPI and Wire so even tho we are using the 'second' peripherals, they are usable as `SPI` and `Wire` :)

### CODE REVIEW

**Comment by ladyada** [comment]
cc @PaintYourDragon

**Comment by maxgerhardt** [comment]
`__SPI0_DEVICE` does not appear in this repo nor in Pico-SDK when doing a Github search, does it affect a library?

**Comment by PaintYourDragon** [comment]
@ladyada Since pins_arduino.h is getting updated here…might be worth adding the DVI CKN/CKP/D0N/D0P etc. pin defs that were desired but overlooked when the board was first added.
ALSO, if the proposed Wire/SPI changes here stick…should the same change be retconned into Feather RP2040 SCORPIO, or is this applicable only to the new “bones” boards?

**Comment by ladyada** [comment]
@maxgerhardt its in the SPI and Wire library files, determines which peripheral is used

**Pull request merged**
