### PR TITLE
Adding a Joystick library, concurrently usable with Keyboard & Mouse

### PR DESCRIPTION
**Pull request by benjaminaigner**
Dear Earle,

because of different use cases, I needed code to emulate Mouse, Keyboard and Joystick at the same time.

This PR adds some lines of code in your RP2040USB files to add the Joystick HID report there,
as well as the library as a git submodule.

Any remarks welcome,
THX for your project.

### CODE REVIEW

**Comment by benjaminaigner** [comment]
@earlephilhower 
THX, no hurry. If you need some changes, I'll gladly adapt the PR.

**Comment by earlephilhower** [comment]
@benjaminaigner couple things found w/the CI system.  We build w/`-Wall -Werror`and you have some warnings in the code:
````
/home/runner/arduino_ide/hardware/pico/rp2040/libraries/Joystick/src/Joystick.cpp:151:34: error: unused parameter 'num' [-Werror=unused-parameter]
  151 | void Joystick_::hat(unsigned int num, int angle)
      |                     ~~~~~~~~~~~~~^~~
cc1plus: all warnings being treated as errors
Using library Joystick at version 1.0.1 in folder: /home/runner/arduino_ide/hardware/pico/rp2040/libraries/Joystick 
exit status 1
````
A simple `(void) num` will take care of that, assuming it really was meant to be ignored.  I didn't check for all errors like this, but you can show them in your own builds by using File-Preferences to enable "All" compiler warnings.

There is also a style test that needs to reformat your changed to RP2040USB.cpp  If you go to the core base directory and run `bash ./tests/restyle.sh` it will run the formatter on all the code, which you can then check in.

**Comment by benjaminaigner** [comment]
Dear @earlephilhower 
oh no, such a stupid mistake to compile without Wall.
* Compiler warnings are removed
* Code is reformatted with astyle

**Review by earlephilhower — APPROVED** [review]

**Comment by benjaminaigner** [comment]
THX for merging and THX for all your hard work on this project!

**Pull request merged**
