### PR TITLE
Add Adafruit Feather RP2040 SCORPIO

### PR DESCRIPTION
**Pull request by PaintYourDragon**
Please excuse the roundabout bungling of my many commits here…I didn’t understand how all the pieces worked at first.

### CODE REVIEW

**Comment by maxgerhardt** [comment]
For my interest, does the Feather RP2040 SCORPIO have an official page on the Adafruit store? I only see references to it in tweets, articles and a youtube video from a year ago. There are [0 matches](https://www.adafruit.com/?q=SCORPIO+&sort=BestMatch) for 'SCORPIO' on the adafruit stite.

**Comment by Andy2No** [comment]
> For my interest, does the Feather RP2040 SCORPIO have an official page on the Adafruit store? I only see references to it in tweets, articles and a youtube video from a year ago.

There's a podcast, dated three weeks ago, that mentions a revised version under development:

https://www.audacy.com/podcast/adafruit-industries-07fde/episodes/desk-of-ladyada-eyespi-2834-tft-revision-amp-scorpio-revisit-aece4

**Comment by Andy2No** [comment]
> youtube video from a year ago. 

The relevant part of the recent YT video starts about 5 and a half minutes in, here:

https://youtu.be/iGL1YvRAKok?t=320

It seems the project was shelved due to difficulty getting the parts, and is now being revived.

**Comment by PaintYourDragon** [comment]
@maxgerhardt The product page is not yet live, but will reside here once ready:
https://www.adafruit.com/product/5650
I would expect it in the next couple of weeks. Currently I’m writing the product tutorial…I could provide preview access if it will help validate this…just understand that some pages are blank placeholders until product photos are ready.

This tweet shows the first panel off the line:
https://twitter.com/adafruit/status/1592702435919024129
…and also explains why Limor (who usually adds Adafruit boards here) had to delegate the task to my less experienced hands. 🙂
Thanks!

**Comment by maxgerhardt** [comment]
I see. Well I don't need access to sensitive internal documents -- if at all and anyone, that would be the one who can merge the PR (@earlephilhower).

Short sanity check though, if the board is basically the Feather RP2040 with an added 5V level shifter, was the flash really changed? Feather RP2040 is declared to use `boot2_w25x10cl_4_padded_checksum` while the SCORPIO uses `boot2_w25q080_2_padded_checksum`, at double the SPI speed.

**Review by earlephilhower — APPROVED** [review]
Thanks for the complete update!  If you need an update when stuffed boards come back, just throw a new PR this way. :)

**Pull request merged**
