### PR TITLE
Fix #919

### LINKED ISSUE #919: PWM glitching/optimization
IMO, this section is a little bit extreme, and disturbing the PWM operation of remaining pins

https://github.com/earlephilhower/arduino-pico/blob/10090b60a9458f4a495e88f8df989401eded7c02/cores/rp2040/wiring_analog.cpp#L100-L102

It's better to just use

```cpp
pwm_init(pwm_gpio_to_slice_num(pin), &c, true);
```

Moreover, to avoid glitch when changing, it's better to use

```cpp
pwm_set_wrap(pwm_gpio_to_slice_num(pin), analogScale);
```

instead of

```cpp
pwm_config_set_wrap(&c, analogScale);
```

Check [**Changing Duty Cycle Dynamically Creates Runt PWM pulse** #10](https://github.com/khoih-prog/RP2040_PWM/issues/10) for more info.

_Originally posted by @khoih-prog in https://github.com/earlephilhower/arduino-pico/issues/918#issuecomment-1280019684_

### PR DESCRIPTION
**Pull request by khoih-prog**
Fix disturbing the PWM operation of remaining pins

### CODE REVIEW

**Comment by khoih-prog** [comment]
HI @earlephilhower 

I rechecked but still I couldn't figure out why `Style, Boards, Package (pull_request)` check failed.

**Comment by earlephilhower** [comment]
> I rechecked but still I couldn't figure out why `Style, Boards, Package (pull_request)` check failed.

Looks like space/tab and empty lines w/trailing spaces.  You can run `./tests/restyle.sh` to run astyle to clean up the source changes.

**Comment by khoih-prog** [comment]
Thanks. Restyled done and OK now.

**Review by earlephilhower — CHANGES_REQUESTED** [review]
I think there are a couple problems here.

* The `pwmInitted` global is still there but ignored.
* The local static bool array[] (which probably should just be a `uint32_t` that's a bitmask to save 24 bytes of RAM) only ever can go from 0->1, but never back to 0.
* Same for the `pwmScaleInitted`, it's a 1-way trip and you can never change the scale or range.

I can do a PR with the `pwm_init` change later in the week (traveling now), so no worries about fixing this one if you're pressed for free time.

**Comment by khoih-prog** [comment]
Good that you'll take care of this. I'm currently on something else. Thanks.

**Comment by earlephilhower** [comment]
Superseded by #926

**Pull request closed without merging**
