### PR TITLE
 Add RP2350B generic/Pimoroni PGA2350 support 

### PR DESCRIPTION
**Pull request by earlephilhower**
Add support for the extra 16 GPIO pins in the menus and core.

### CODE REVIEW

**Comment by earlephilhower** [comment]
@NollKollTroll, this PR should make the GPIOs > 39 work for everything but PIO-based usage (i.e. no Tone(40) or SerialPIO(45, 46)).  The PSRAM should also come up automatically w/the Pimoroni PGA2350.  If you have a change, could you give this a try?  I still haven't found my wirewrap pen to start futzing w/the PGA2350...

**Comment by NollKollTroll** [comment]
I am trying to get it working on my end, will have to learn how to insert the PR into my pulled source. Will be back when I have tested the fixes.

**Comment by NollKollTroll** [comment]
Failing to understand how to properly select/load the modified PR-code in the arduino-IDE, I finally managed to make a fake 4.0.2 in the .arduino15 tree that kinda works. Don't know what is my fault and what is the failings of the PR-code...

- When selecting Pimoroni PGA2350, build fails with:
`cc1: fatal error: /home/adam/.arduino15/packages/rp2040/hardware/rp2040/4.0.2/boot2/rp2350/boot2_w25q64jv_4_padded_checksum.S: No such file or directory
compilation terminated.`

- When selecting Generic RP2350 and adding `#define RP2350_PSRAM_CS (47u)` in `generic_rp2350/pins_arduino.h`, PSRAMTest.ino builds and executes correctly.

**Comment by NollKollTroll** [comment]
Tried again, and seem to have installed a correctly updated 4.0.2 since I get new menu options, like PSRAM_CS.

Choosing `Generic RP2350` and updating the different menu options, `PSRAMTest.ino` compiles and runs correctly.
Setting a faulty PSRAM_CS produces a faulty memory test as expected.

Choosing `Pimoroni PGA2350` fails in the same way:
`cc1: fatal error: /home/adam/.arduino15/packages/rp2040/hardware/rp2040/4.0.2/boot2/rp2350/boot2_w25q64jv_4_padded_checksum.S: No such file or directory
compilation terminated.`

**Pull request merged**
