### PR TITLE
Arduino Nano R2040 Connect Nina pins access with WiFiNINA lib

### PR DESCRIPTION
**Pull request by jandrassy**
below is the example for the RGB LED pins on Arduino Nano R2040 Connect (the LEDs are connected to the NINA module as are boards pins labeled A4 to A7)
The pinMode and digitalWrite functions here are overloaded versions  with a parameter of type NinaPin from nina_pins.h.
The implementations are in the WiFiNINA library but the NinaPin type and the declarations are in the nina_pins.h in `#ifdef ARDUINO_NANO_RP2040_CONNECT`.

@khoih-prog do you have a Nano Connect? If yes could you please test this? (with __has_include removed please)

```
#include <WiFiNINA.h>

void setup() {
  pinMode(LEDR, OUTPUT);
  pinMode(LEDG, OUTPUT);
  pinMode(LEDB, OUTPUT);
}

void loop() {
   digitalWrite(LEDR,HIGH); // Turn On RED LED
   delay(250);
   digitalWrite(LEDR,LOW); // Turn Off RED LED

   digitalWrite(LEDG,HIGH); // Turn On GREEN LED
   delay(250);
   digitalWrite(LEDG,LOW); // Turn Off GREEN LED

   digitalWrite(LEDB,HIGH); // Turn On BLUE LED
   delay(250);
   digitalWrite(LEDB,LOW); // Turn Off BLUE LED
}
```

### CODE REVIEW

**Comment by earlephilhower** [comment]
@jandrassy you can't manually edit the boards.txt file, it's machine generated.  CI is failing because of this.  You'll just need to update the makeboards.py file and regenerate it...

**Comment by jandrassy** [comment]
> @jandrassy you can't manually edit the boards.txt file, it's machine generated. CI is failing because of this. You'll just need to update the makeboards.py file and regenerate it...

sorry. It should be ok now.

**Comment by khoih-prog** [comment]
@jandrassy 

If you still keep `__has_include` as in [nina_pins.h#L16-L20](https://github.com/earlephilhower/arduino-pico/blob/64f9c884822d97ac92105748c4d4ea3eceb96935/variants/arduino_nano_connect/nina_pins.h#L16-L20) while the `__has_include` issue hasn't been found and fixed, I think we still have compile errors for even with `WiFiNINA`.

Isn't it better for now to remove `__has_include` and NINA_ATTRIBUTE-related code?

**Comment by jandrassy** [comment]
> @jandrassy
> 
> If you still keep `__has_include` as in [nina_pins.h#L16-L20](https://github.com/earlephilhower/arduino-pico/blob/64f9c884822d97ac92105748c4d4ea3eceb96935/variants/arduino_nano_connect/nina_pins.h#L16-L20) while the `__has_include` issue hasn't been found and fixed, I think we still have compile errors for even with `WiFiNINA`.
> 
> Isn't it better for now to remove `__has_include` and NINA_ATTRIBUTE-related code?

your PR removes it. git will merge the changes if my PR is accepted

**Comment by jandrassy** [comment]
@earlephilhower are you OK with the `arduino_nano_connect.build.board` name change in this PR from
`ARDUINO_ARDUINO_NANO_RP2040_CONNECT` to `ARDUINO_NANO_RP2040_CONNECT`
so it matches ifdefs in the WiFiNINA library?

**Comment by khoih-prog** [comment]
> @earlephilhower are you OK with the arduino_nano_connect.build.board name change in this PR from
> ARDUINO_ARDUINO_NANO_RP2040_CONNECT to ARDUINO_NANO_RP2040_CONNECT
> so it matches #ifdefs in the WiFiNINA library?

IMO, modify the board name from `ARDUINO_ARDUINO_NANO_RP2040_CONNECT` to `ARDUINO_NANO_RP2040_CONNECT` is a must to compile for WiFiNINA library to use LEDx and A4-A7

I tested and everything is OK now with the current modified #404, for either WiFiNINA or WiFiNINA_Generic library.

**Comment by earlephilhower** [comment]
> @earlephilhower are you OK with the `arduino_nano_connect.build.board` name change in this PR from `ARDUINO_ARDUINO_NANO_RP2040_CONNECT` to `ARDUINO_NANO_RP2040_CONNECT` so it matches #ifdefs in the WiFiNINA library?

That's fine with me.  I wasn't sure what they were calling it and took a guess at it and ended up redundantly redundant.  I'm good to go with this patch, and since @khoih-prog reported success, it'll merge presently...

Thanks again, guys, for figuring this out!

**Pull request merged**
