### PR TITLE
Updated listfiles example and added CardInfo example

### PR DESCRIPTION
**Pull request by richteel**
- Updated listfiles example to make it clear for some using SPI1 what to do to get the code working. The if block checking MISO pin assignment, could be removed and a line(s) could be added with a comment showing SD.begin() with SPI1 specification. I had already created the if block before the thought of a simple comment came to mind, so I left the if block there.
- Added CardInfo after finding the code posted by Renzo Mischianti at https://mischianti.org/raspberry-pi-pico-and-rp2040-boards-how-to-use-sd-card-5/. I took the code and modified it to mirror listfiles where applicable.

I have a CircuitPython project that I'm converting to C++ and needed to reference these two examples. I ran into a few delays, which were resolved once I realized I could specify the SPI being used, and came across the code that Renzo had on his site. I think the addition of these changes will be helpful to others as well. If you like the code as is great, but if you would like the if statements in listfiles to be replaced with a comment, feel free to do so, or let me know and I will do it.

### CODE REVIEW

**Comment by richteel** [comment]
It looks like some files were added that was not intended. Let me clean it up. I only intended to add/edit the two example files in the SD library.

**Comment by richteel** [comment]
It looks like there was only one file unintentionally added. It has been removed.

**Review by earlephilhower — APPROVED** [review]
Thanks, these look very nice.   I really appreciate the effort to document this stuff for beginners!

Are you done with edits at this point, or should I wait to merge?

**Comment by richteel** [comment]
Thank you, I'm done with the edits.

--- Happy New Year ---

**Pull request merged**
