### PR TITLE
Adds support for Challenger RP2040 WiFi boards

### PR DESCRIPTION
**Pull request by PontusO**
This adds support for our new Challenger RP2040 board with integrated WiFi onboard.

### CODE REVIEW

**Comment by earlephilhower** [comment]
@PontusO thanks, but there is a problem.

I use an automated script to build boards.txt (makes it possible to, say, add a menu to all types or a new debug mode w/o manually hacking 100 spots).  You'll need to update https://github.com/earlephilhower/arduino-pico/blob/master/tools/makeboards.py and run it to overwrite `boards.txt` for the CI to pass.

Can you update the script and re-push?

**Comment by PontusO** [comment]
Absolutely. Do I understand it correctly that I simply add my board at the end with a MakeBoard statement ?

**Comment by earlephilhower** [comment]
> Absolutely. Do I understand it correctly that I simply add my board at the end with a MakeBoard statement ?

Basically, yes.  Make sure you update the flash boot2, memory, USB ID, etc. options but that's the gist of it.  That 1-line will make all 300 you had to manually add in this PR. :)

**Comment by PontusO** [comment]
Excellent stuff =)

**Pull request merged**
