### PR TITLE
Fix PicoProbe CMSIS restart of second core

### LINKED ISSUE #1687: core1 not starting when uploading via CMSIS-DAP and FreeRTOS tasks not starting
Probably related to #676 and #402.

When using this `platformio.ini`, core1 (i.e. `setup1()` and `loop1()`) do not start until the board is reset (by unplugging and re-plugging usb)
```ini
[env:pico-debug]
build_type = debug
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
platform_packages =
   framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#master
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
```
Similarly FreeRTOS tasks don't run with when uploaded via CMSIS-DAP, when using this code in `setup()`
```cpp
xTaskCreate(ledBlinkTask, "ledBlinkTask", 4096, NULL, configMAX_PRIORITIES - 1, NULL);
vTaskStartScheduler();
```

Using the debugger, the code gets to `rtosFatalError()`, but the onboard LED does not blink
```cpp
/*  ---------------------------------------------------------------------------*\
    Usage:
	called on fatal error (interrupts disabled already)
    \*---------------------------------------------------------------------------*/
extern "C"
void rtosFatalError(void) {
    prvSetMainLedOn(); // Main LED on.

    for (;;) {
        // Main LED slow flash
        sleep_ms(100);
        prvBlinkMainLed();
        sleep_ms(2000);
        prvBlinkMainLed();
    }
}
```

The other issues have been fixed via a PR, but it looks like this is the same problem

### PR DESCRIPTION
**Pull request by earlephilhower**
For some reason `program ... reset" causes OpenOCD to leave the chip in a state where the 2nd core does not come up properly, leading to problems in FreeRTOS and others.

Use a separate reset sequence after programming to work around the issue.

Fixes #1687

### CODE REVIEW

**Comment by earlephilhower** [comment]
@maxgerhardt could you please update your P.IO config script to use the separated resets, too?

**Comment by maxgerhardt** [comment]
Equalized in https://github.com/maxgerhardt/platform-raspberrypi/commit/0742fd4f880ec897fa5a63294e3ffedd0aff99ad.

**Comment by earlephilhower** [comment]
One minor thing, I think we need an `-c exit` at the end or it seems (in the IDE) it will leave OpenOCD running

**Comment by maxgerhardt** [comment]
The `shutdown;` at the end should equivalently take care of this (as it did before)

**Pull request merged**
