### PR TITLE
support native usb as host

### PR DESCRIPTION
**Pull request by hathach**
add a new usbstack menu to add new macro `USE_TINYUSB_HOST` which will configure the native usb as host. print to Serial will do nothing (like NO_USB). 
- Tested with https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/353 new examples/Host/Simple/host_device_info work well.

Screenshot from 2023-12-19 17-42-18

### CODE REVIEW

**Comment by earlephilhower** [comment]
This looks great!  But, do we need to update the Adafruit TinyUSB library as well with this PR?

**Comment by shreeve** [comment]
@earlephilhower - It looks like https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/353 is the PR for Adafruit TinyUSB. Once that and this are merged, we can finally have access to the native USB Phy as Host! :-) Wahoo!

**Comment by hathach** [comment]
@earlephilhower sure thing, let me merge and release tinyusb first then update this PR.

**Comment by hathach** [comment]
update tinyusb lib and skip the native host example in ci

**Review by earlephilhower — APPROVED** [review]
Thanks again!

**Comment by shreeve** [comment]
Fantastic! Great job @hathach and @earlephilhower !!!

**Pull request merged**
