### PR TITLE
feat: Implemented support for filters and removable routes in WebServer

### PR DESCRIPTION
**Pull request by ayushsharma82**
This PR implements filters and removable routes in RP2040 arduino core, making it API compatible with recent changes to ESP32 & ESP8266 WebServer API.

> [!NOTE]
> Please merge when all ESP32 repo pull requests mentioned below are merged.

#### Reference (Recent additions to ESP32 WebServer API): 
- https://github.com/espressif/arduino-esp32/pull/9832
- https://github.com/espressif/arduino-esp32/pull/9842
- https://github.com/espressif/arduino-esp32/pull/9851

#### Reference (Recent addition to ESP8266 WebServer API):
- https://github.com/esp8266/Arduino/pull/9152

__Noteable Changes:__
1. Request Filters (`setFilter`)
2. Removable Routes (`removeRoute`, `removeHandler`, `_removeRequestHandler`)

### CODE REVIEW

**Comment by earlephilhower** [comment]
You need to run `tools/restyle.sh` to get the formatting correct for the repo here, and `(void)` out an unused parameter to get through CI.  OTW, seems nice and thanks for including an example!

**Comment by ayushsharma82** [comment]
Apparently, a lot of files weren't conforming to suggested format. I ran `tests/restyle.sh`.

**Comment by ayushsharma82** [comment]
CI style check failed. Can this be due to different `astyle` package version on my local machine? I have this on my PC:  `Artistic Style Version 3.5`.

**Comment by ayushsharma82** [comment]
Fixed example & formatting. 

*PS: I formatted WebServer folder only instead of whole library.*

**Comment by ayushsharma82** [comment]
Fixed everything and tested locally. This should pass all CI tests.

Also, ESP32 PRs are merged therefore this PR is ready for merger too.

**Pull request merged**
