### PR TITLE
Adding capability to enable timeout for I2C

### PR DESCRIPTION
**Pull request by ZinnerC**
This should allow to have the timeout enabled which is provided through "i2c_read_blocking_until".

Based on first tests the I2C bus does not "hang" anymore.
However, executing the "getTimeoutFlag()" did not give conclusive results.

In some scripts it was did show "0" (no timeout occured) and in others (bigger project) it did not show "1" eventough the I2C run into timeout otherwhise the MCU would have reset.

### CODE REVIEW

**Comment by ZinnerC** [comment]
Just wanted to check in. Is something not working?
I used the changes on my pico and it seamed to work.
Looking forward to see if I was able to contribute. 😊

**Comment by earlephilhower** [comment]
Sorry, I just finished my Camino and won't be home for a few more days.  I'll be able to look at this then.  In the meantime, it looks like there were some style errors in CI.  Can you look into them?

**Comment by ZinnerC** [comment]
I will check if I will be able to have a look. Currently on a business trip in China and not sure when I will have time. But let's see.
Thanks, for the reply.

**Comment by earlephilhower** [comment]
No worries about the style stuff.  Just some trailing spaces I've just cleaned up in the branch.  The code also looks good to me.  Thanks again for the PR!

**Comment by ZinnerC** [comment]
Thank you very much for checking and adjusting the style.

**Pull request merged**
