### PR TITLE
add 0xCB Helios

### PR DESCRIPTION
**Pull request by Conor-Burns**
Adding 0xCB Helios
[source](https://github.com/0xCB-dev/0xCB-Helios)

### CODE REVIEW

**Comment by Conor-Burns** [comment]
Waiting on https://github.com/raspberrypi/pico-sdk/pull/1174

**Comment by earlephilhower** [comment]
@Conor-Burns we don't need to wait for the SDK change to add a board here, unless you're changing something beyond their header config file.  None of those constants are used, only what you define here in your `variant` directory.

**Comment by Conor-Burns** [comment]
Oh alright - thanks!

**Comment by Conor-Burns** [comment]
Thank you!

**Comment by Conor-Burns** [comment]
Is there a fixed release cycle?

**Comment by earlephilhower** [comment]
Every 2-4 weeks, but it depends on whether or not anything "interesting" has been merged.  Probably will do a 2.7.1 this weekend to push out the new menu structure and upload options.

**Comment by Conor-Burns** [comment]
Awesome! 👍

**Comment by maxgerhardt** [comment]
Boot2 source is selected as `boot2_w25q080_2_padded_checksum` but the BOM in https://github.com/0xCB-dev/0xCB-Helios W25Q128JVPIQ? Did you double check that that works?

**Comment by Conor-Burns** [comment]
Ah thanks for the heads up!
It does work but I'm gonna make a PR later 👍

**Pull request merged**
