### PR TITLE
optimizes core1 stack handling

### PR DESCRIPTION
**Pull request by traxanos**
as discussed in ticket #1814 , a suggestion for optimizing batch processing for core1 incl matching helper functions.
i tried to adopt your naming scheme. but feel free to customize it if you don't like it.
i hope this is as you envisioned it.

### CODE REVIEW

**Comment by traxanos** [comment]
Is it possible that the global macros do not access main.c in the framwork?

**Comment by traxanos** [comment]
I have also made another variant.
https://github.com/earlephilhower/arduino-pico/compare/master...OpenKNX:arduino-pico:optimizes-core1-stack-alternative

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Thanks, but the problem with the PR here is that it's not usable in the Arduino IDE, only from the P.IO config.  `#define`s can't really be set by the app.

I did like the 2nd version you linked, though.  The formatting will need to match the core's (tools/restyle.sh), but OTW it looked OK to me.

**Comment by traxanos** [comment]
i have now adopted suggestion 2 as mr and hope that now fits. tools/restyle.sh does not exist. and tests/restyle.sh does not run on windows.

**Review by earlephilhower — APPROVED** [review]
Thanks!

**Comment by traxanos** [comment]
i have removed the 4 whitespaces for style check

**Pull request merged**
