### PR TITLE
Add WIZnet W55RP20-EVB-Pico board

### PR DESCRIPTION
**Pull request by wiznet-mason**
The W55RP20 is a SiP chip that integrates the RP2040 with WIZnet's W5500 and 2MB Flash.
https://docs.wiznet.io/Product/ioNIC/W55RP20/overview

### CODE REVIEW

**Comment by earlephilhower** [comment]
Thanks!  Looks like you need to check in the modified `package/package_pico_index.template.json` file (modified/built by `makeboards.py` per the CI failure.

**Comment by maxgerhardt** [comment]
@wiznet-mason recheck CI, it's complaining about 
```
/home/runner/arduino_ide/hardware/pico/rp2040/libraries/lwIP_w55rp20/src/wiznet_pio_spi.c:79:23: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
   79 |     for (int i = 0; i < count_of(wiznet_pio_spi_state); i++) {
      |                       ^
cc1: all warnings being treated as errors
```

**Comment by earlephilhower** [comment]
Ping, @wiznet-mason .  We can't edit your repo, so you'll need to fix the CI warnings from gcc (use `File->Preferences->Compiler Warnings->All` to mimic the `-wall -werror` we run in CI).

**Comment by wiznet-mason** [comment]
Thank you very much for all the advice. I’ll try again and commit.

**Comment by wiznet-mason** [comment]
Thank you very much!

**Comment by maxgerhardt** [comment]
Aww, the board was not added to the README.md list though!

**Pull request merged**
