### PR TITLE
modify pins_arduino.h file.

### PR DESCRIPTION
**Pull request by Arya11111**

### CODE REVIEW

**Comment by Arya11111** [comment]
modify pins_arduino.h file.

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Please start with a fresh branch from latest master.  This PR is not mergeable with the current code,

**Comment by Arya11111** [comment]
Is that so?

**Comment by earlephilhower** [comment]
No, still no good.  You have 23 files changed in the PR.  It’s still not possible to merge.  You should have 1 or 2 files in total changed on a proper one updating a pins file.

**Comment by Arya11111** [comment]
Sorry，I already merge the latest upstream. This is the new change，please note.

**Pull request merged**
