### PR TITLE
Add options to disable USB or USB Serial

### PR DESCRIPTION
**Pull request by tvlad1234**
I added options to the 'USB Stack' menu in Board Config which allow for disabling USB Serial or the USB peripheral entirely. This is useful in situations where the USB peripheral is already being used by code running on the second core and cannot be disturbed by user code.

### CODE REVIEW

**Comment by tvlad1234** [comment]
I forgot to add an include to the "No USB" config

**Comment by tvlad1234** [comment]
I fixed the problem, sorry about that, I'm quite new to using Git. Should I open another PR?

**Comment by earlephilhower** [comment]
That's fine, if you made a completely new branch.  If you changed on this branch, then just push it to GH and then your changes will automatically be added to this PR (and you can just "reopen"

**Comment by earlephilhower** [comment]
Oops, I see you used `master` and did a `git push --force` (hence overwriting things irretrievably).    So, in that case, just open a new PR.

**Comment by tvlad1234** [comment]
Alright, I am opening a new PR.

**Pull request closed without merging**
