### PR TITLE
add board Pimoroni Pico Plus 2

### PR DESCRIPTION
**Pull request by SamHalvoe**
Hi, I have added the Pimoroni Pico Plus 2 board.
This is the first board (and contribution) I have added. I hope I haven't done anything wrong.
Best Regards
Sam Halvoe

### CODE REVIEW

**Review by earlephilhower — APPROVED** [review]
LGTM, thanks!

**Comment by earlephilhower** [comment]
I think you forgot to check in your modified `makeboards.py`

**Comment by SamHalvoe** [comment]
I checked in my modified makeboards.py and added the board to the readme. Also updated pins_arduino.h (added PSRAM_CS among others)

**Comment by earlephilhower** [comment]
Thx!

**Pull request merged**
