### PR TITLE
Add -DBOARD_NAME="{build.board}"

### PR DESCRIPTION
**Pull request by khoih-prog**
Add -DBOARD_NAME="{build.board}" to Compile patterns to facilitate using BOARD_NAME in sketches

For example

```
void setup() 
{ 
  // Open serial communications and wait for port to open:
  Serial.begin(115200);
  while (!Serial);

  Serial.print("Ethernet Test on "); Serial.println(BOARD_NAME);
}
void loop() 
{
}
```

to print

```
Ethernet Test on RASPBERRY_PI_PICO
```

### CODE REVIEW

**Comment by per1234** [comment]
@khoih-prog is the `BOARD_NAME` macro name an established convention?

If not, I'm wondering if it would be better to use the `ARDUINO_` prefix, as is done for `-DARDUINO_{build.board}` `-DARDUINO_ARCH_{build.arch}`. This creates a "namespace" of sorts for the platform-generated macros to avoid name collisions with macros defined elsewhere, which is especially likely with globally defined macros. On the other hand, maybe it's a bit odd to use the `ARDUINO_` for macros which don't have a precedent  in the official platforms?

**Comment by khoih-prog** [comment]
The `BOARD_NAME` has been used in the STM32 core

[**platform.txt** #L93)](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/platform.txt#L93)

```
# Build information's
build.info.flags=-D{build.series} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} -DBOARD_NAME="{build.board}" -DVARIANT_H="{build.variant_h}"
```
---

If we need to display which board we're using (for example, for library/core writer to know if the user uses or selects the correct board) It's better than we have to use harder way

```
#if defined(ARDUINO_SAMD_MKR1000)
  #define BOARD_NAME      "SAMD_MKR1000"
#endif

#if defined(ARDUINO_RASPBERRY_PI_PICO)
  #define BOARD_NAME      "RASPBERRY_PI_PICO"
#endif
```

This way, users has to know how to access `board.txt` to know 

```
rpipico.build.board=RASPBERRY_PI_PICO
```
to use `-DARDUINO_{build.board}` => `#if defined(ARDUINO_RASPBERRY_PI_PICO)`

while using `BOARD_NAME`, users don't have to know anything about `board.txt` and `platform.txt`

---

This is very minor and not important feature, just good to have.

**Comment by khoih-prog** [comment]
One more note that in [ArduinoCore-mbedcore](https://github.com/arduino/https://github.com/arduino/ArduinoCore-mbed), we have the similar `BOARD_NAME` definition @ [pins_arduino.h #L67](https://github.com/arduino/ArduinoCore-mbed/blob/master/variants/RASPBERRY_PI_PICO/pins_arduino.h#L67)

```
#define BOARD_NAME			"RaspberryPi Pico"
```

**Comment by per1234** [comment]
>The `BOARD_NAME` has been used in the STM32 core

>in ArduinoCore-mbed, we have the similar BOARD_NAME definition

Thanks for the clarification. That is a fairly significant precedent, which I was not aware of. This sort of thing is most valuable when done consistently across the ecosystem, so I think you made the right choice.

Ideally, there would be a formal official definition of these standards. There is (in my biased opinion) currently pretty good documentation about the platform components which are required or provided automatically by the build system, but essentially no formal documentation about the recommended/expected components (https://github.com/arduino/arduino-cli/issues/985), which means there is not a very good mechanism for documenting the current standards or proposing new ones. Currently the approach is to just analyze what has been done in the official platforms.

>This is very minor and not important feature, just good to have.

I fully understand the motivation behind the proposal and why `-DARDUINO_{build.board}` is not an effective substitute in the use cases for `BOARD_NAME`.

**Comment by khoih-prog** [comment]
That's something waiting for you, as an long-time insider, to propose and make change.

**Comment by earlephilhower** [comment]
Don't we need some escape magic to get this define as a quoted string?  I think bash/cmd will just eat the quotes in platform.txt while parsing out args to the compiler.

**Comment by khoih-prog** [comment]
I haven't seen any issue yet. This way has been used and tested in several platforms and OSes without any problem.

**Comment by earlephilhower** [comment]
Ok, thx!

**Pull request merged**
