### PR TITLE
Add ArtronShop RP2 Nano board

### PR DESCRIPTION
**Pull request by maxpromer**
Thanks Earle F. Philhower, III for hard work ! We are ArtronShop company and we make new RP2040 dev board it name is **ArtronShop RP2 Nano** it a Arduino Nano compatible ! all pin and most pin function is like Arduino Nano and you can replace Arduino Nano by ArtronShop RP2 Nano

This board are in manufacturing process but we have a sample board for test and have fritzing library

ArtronShop RP2 Nano

I tested the pull request on real devices and it works !

### CODE REVIEW

**Comment by Andy2No** [comment]
The link to ArtronShop RP2 Nano, above, appears to be broken.  It's giving a message that says "Error Fetching Resource".

**Comment by maxpromer** [comment]
> The link to ArtronShop RP2 Nano, above, appears to be broken. It's giving a message that says "Error Fetching Resource".

I updated image link and now image show up.

i run makeboards.py again for fixed workflow not pass so plz approval workflow again, Thank you !

**Comment by earlephilhower** [comment]
This needs an update to the latest master since I don't have permission to do it myself.  Could you re-merge with the latest `git head` and re-push the PR?

**Comment by maxpromer** [comment]
> This needs an update to the latest master since I don't have permission to do it myself. Could you re-merge with the latest `git head` and re-push the PR?

I click "merge master" and awaiting approval workflow again .... :-)

**Comment by maxpromer** [comment]
OK i found last commit are update makeboards.py so i will close it then update makeboards.py and run then open PR again

**Pull request closed without merging**
