### PR TITLE
add DFRobot Beetle RP2040 boards V1.0.0

### PR DESCRIPTION
**Pull request by Arya11111**
The order of positions has been modified.

### CODE REVIEW

**Review by earlephilhower — APPROVED** [review]
Thanks!

**Review by earlephilhower — CHANGES_REQUESTED** [review]
So I see you changed them position in the script, but you also still need to rerun the script to make a fixed boards file.

**Comment by Arya11111** [comment]
Sorry, the script has already been run, thanks.

**Comment by Arya11111** [comment]
Sorry, the script has already been run, thanks.

**Review by earlephilhower — APPROVED** [review]

**Pull request merged**
