### PR TITLE
Add correct boot source to helios

### PR DESCRIPTION
**Pull request by Conor-Burns**
thank you @maxgerhardt

### CODE REVIEW

**Comment by maxgerhardt** [comment]
Can we also add it in the array for the General board selection? 

https://github.com/earlephilhower/arduino-pico/blob/0406affd097525eb7eca0bc134b8cb41f42cc3a6/tools/makeboards.py#L68-L75

You did test a firmware built on this boot2 file on real hw?

**Comment by earlephilhower** [comment]
Ping @Conor-Burns .  Did you have a chance to double check this new flash BOOT2 does work properly on the board?  I can add the missing boot2 options to generic after this, no worries.

**Comment by Conor-Burns** [comment]
Hi @earlephilhower sadly not yet, sorry for beeing unresponive. I just tried to build it locally but I'm at a loss on how to test it / compile.
Could you point me in the right direction?

**Comment by earlephilhower** [comment]
No worries!

If you've got a `git clone` you're running from, just select the board from the menus, run an example (I'd suggest the LittleFS SpeedTest since it's very flash I/O heavy) ans make sure it runs w/the new BOOT2.s (the core will compile the .S automatically, no need to do anything other then point it to the right file like you did).

**Comment by Conor-Burns** [comment]
but how do i run from a git clone?

**Comment by earlephilhower** [comment]
No boards manager used, that's only for d/l'ing releases.

If you place the git clone in the proper spot, it will be detected (and say "RP2040/... (in sketchbook") in the Boards menu.  See https://github.com/earlephilhower/arduino-pico#installing-via-git

**Comment by Conor-Burns** [comment]
nvm got it - thanks

**Comment by Conor-Burns** [comment]
Before 
image
After
image

I'd say we keep it as is - what do you think?

**Comment by earlephilhower** [comment]
The issue is more about timing being out of spec.  The new one is more conservative, probably because the flash itself has slower timings, so it will have a little lower performance.  It'll probably work but at certain temperatures or certain slower-but-legal chips you can have timing problems and fail reads or writes.

So, I'd say use the slower one you've just selected for safety.  We're not normally flash speed limited for microcontroller apps.

**Comment by Conor-Burns** [comment]
Okay thank you for the clarification :+1: 

Then I'd say it's ready to merge.

**Comment by Conor-Burns** [comment]
🙏

**Pull request merged**
