### PR TITLE
add adafruit Adalogger feather

### PR DESCRIPTION
**Pull request by ladyada**

### CODE REVIEW

**Comment by earlephilhower** [comment]
Looks like the order of boards changed in makeboards.py.  Can you please re-run it to fix the CI failure?

**Comment by earlephilhower** [comment]
Ping @ladyada .  I'd like to get a release out this week and would love to get this in, too.  Because another board was merged before this, you'll need to pull the latest master and rerun the `makeboards.py` script to get things all cleaned up.  Thx!

**Comment by hathach** [comment]
Thank you @earlephilhower for kindly reminder, I have rebased and re-run the makeboards.py, hopefully it is good enough.

**Comment by ladyada** [comment]
woops sorry was asleep - thank you both :)

**Pull request merged**
