### PR TITLE
Fix WiFiNINA issue for Arduino Nano Connect

### PR DESCRIPTION
**Pull request by khoih-prog**
Fix [#373](https://github.com/earlephilhower/arduino-pico/issues/373)

### CODE REVIEW

**Comment by khoih-prog** [comment]
Close. To use the better modified #404

**Comment by jandrassy** [comment]
@khoih-prog sorry, my PR doesn't fix the __has_include problem. this PR was the right fix. they merge

**Comment by khoih-prog** [comment]
@jandrassy 

I tested your PR #404, with this modified `nina_pins.h` (to remove all __has_include-related code) and all is OK.

```
/* Taken from https://github.com/arduino/ArduinoCore-mbed/tree/master/variants/NANO_RP2040_CONNECT */

#ifndef _NINA_PINS_
#define _NINA_PINS_

/******************************************************************************
 * INCLUDE
 ******************************************************************************/

#include "Arduino.h"

/******************************************************************************
 * TYPEDEF
 ******************************************************************************/

int getAnalogReadResolution();

class NinaPin {
public:
	NinaPin(int _pin) : pin(_pin) {};
	int get() {
		return pin;
	};
	int analogReadResolution() {
		return getAnalogReadResolution();
	};
	bool operator== (NinaPin const & other) const {
		return pin == other.pin;
	}
	//operator int() = delete;
	__attribute__ ((error("Change me to a #define"))) operator int();
private:
	int pin;
};

extern NinaPin  LEDR;
extern NinaPin  LEDG;
extern NinaPin  LEDB;
extern NinaPin  A4;
extern NinaPin  A5;
extern NinaPin  A6;
extern NinaPin  A7;

#define NINA_PINS_AS_CLASS

/******************************************************************************
 * FUNCTION DECLARATION
 ******************************************************************************/

void      pinMode     (NinaPin pin, PinMode mode);
PinStatus digitalRead (NinaPin pin);
void      digitalWrite(NinaPin pin, PinStatus value);
int       analogRead  (NinaPin pin);
void      analogWrite (NinaPin pin, int value);


#endif /* _NINA_PINS_ */
```

This PR can't fix the LEDx / A4-A7 issue because of no `nina_pins.cpp`, and without the `board.txt`  such as in your #404

I haven't checked why your #49404 can't be merged. Can you have a closer look.

**Comment by jandrassy** [comment]
@khoih-prog  the code in your previous comment is a merge of 403 and 404. In my PR I didn't remove the __has_include part because I still hoped for a solution. I spent hours on the __has_include problem.

**Comment by khoih-prog** [comment]
I think it's **better you update your PR** to solve the issue. Just drop the unnecessary `__has_include` because this is just a warning for a must-have error (w/o `WiFiNINA.h`).

If you'd still like to keep you PR open until final solution for `__has_include`, I can create a new PR, merging this #403 and your #404 to have a temporary working solution for now. Just let me know.

**Comment by jandrassy** [comment]
@khoih-prog I think those are two different problems. the severity of _has_include is much larger and my PR has a potentially breaking change. it changes the name of the board.
so please recreate this PR. is solves compilation of any WiFiNINA sketch. my PR only solves the unofficial RGB example (and 4 analog ports).
my PR is OK. it only waits for Earl to start the checks and review the PR.

**Comment by khoih-prog** [comment]
@jandrassy 

OK. Reopen now.

**Comment by earlephilhower** [comment]
@jandrassy @khoih-prog I do apologize again, but I a still a bit confused as to the status here.  Should this or the other PR (or both) be merged, is there still work to do, is there something I need to do on my end also (note that I don't have an Arduino Nano Connect...)?

**Comment by khoih-prog** [comment]
@earlephilhower 

I think you can merge this PR first. Then @jandrassy will rebase the #404 and also to remove all `__has_include`-related code. Then you can merge #404 then.

**Comment by khoih-prog** [comment]
@earlephilhower @jandrassy 

I have Nano_RP2040_Connect and will retest the modified #404 and let you know if everything is OK then to help make decision.

**Comment by jandrassy** [comment]
@earlephilhower , please merge this PR

**Comment by earlephilhower** [comment]
Done, @jandrassy .  @khoih-prog is yours good to go, too?

**Comment by khoih-prog** [comment]
Thanks @earlephilhower 

@jandrassy ,
Please rebase and modify #404.  I'll test and let you know then.

**Comment by jandrassy** [comment]
@khoih-prog done

**Comment by bjoerngiesler** [comment]
Ping on this.

Compiling a sketch using WiFiNINA gives me "undefined reference to getAnalogReadResolution()". If I create a function
int getAnalogReadResolution() { return 12; }
WiFi.localIP() hangs.

Question 1 - who should define getAnalogReadResolution()? I don't find it in the source.
Question 2 - what should it output to not make anything hang?

**Comment by nakeze** [comment]
I just started with the nano connect and also have the compiling error "undefined reference to getAnalogReadResolution()".
With the board configuration "Arduino MbedOS Nano board -> Arduino Nano RP2040 connect", the problem do not exist and calls to analogRead(NinaPin pin) function is able to return a correct value. 

I tried to replace the call for getAnalogReadResolution , it compiles but the analogRead() functions returns 0 and is executed in a microsecond. 

I used Kdiff to see differences in the variants files from the two libraries,  found in the nina_pins.h what was discussed here :
`
#if __has_include("WiFiNINA.h")
#  define NINA_ATTRIBUTE
#else
#  define NINA_ATTRIBUTE __attribute__ ((error("Please include WiFiNINA.h to use this pin")))
#endif
`
and the NINA_ATTRIBUTE set in the analogRead(NinaPin) lines at the end of the file.

 The pins_arduino.h files are also different. 
There are also files that exist in one folder and not in the other. 

Adding the NINA_ATTRIBUTE gives a different error :
error: call to 'analogRead' declared with attribute error: Please include WiFiNINA.h to use this pin

**Pull request merged**
