### PR TITLE
Fixes issue #2454: I2C issue: Ceva BNO085 IMU is not correctly detected

### PR DESCRIPTION
**Pull request by Rasmusfk**
This fixes issue #2454, and has been tested with 4 other I2C IC's which still works after the fix.

### CODE REVIEW

**Comment by Rasmusfk** [comment]
Oh, and by the way this also removes the now unused _probe() function.

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Thanks, but this isn't going to work in general  Translating a 0-byte write into a 1-byte read was discussed and dismissed when the core came out.  In your particular case it may fix things, but in general there were significant issues seen.

The Adafruit folks chimed in on the existing implementation way back when, https://github.com/earlephilhower/arduino-pico/issues/38 (and other issues/prs later).  IIRC, it boiled down to 0-byte writes are guaranteed no-ops on the device, while reads to invalid registers could either (falsely) fail or change chip state causing an error later on..

If detection is iffy with the current code on your setup (and FWIW I know several drone folks using the core so they might be using the same chip if not PCB) then it's possible there's a pull-up/down strength or timing issue.

It's also possible the existing bit banging core is sampling on the wrong edge or not obeying setup/hold timing...if you see a timing or edge issue in the bitbang code, I'm happy to get PRs to adjust that.  But we can't replace a write with a read here.

**Comment by dquadros** [comment]
> Thanks, but this isn't going to work in general Translating a 0-byte write into a 1-byte read was discussed and dismissed when the core came out. In your particular case it may fix things, but in general there were significant issues seen.
 

Not knowing the history of this feature, I was going to ask exactly this.

**Comment by Rasmusfk** [comment]
Ok, thanks! I just assumed that as the Pico SDK used the read-1 method, then it would be ok in general:
https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#group_hardware_i2c
I'll look more into the timing, and see if I can identify the issue.

**Comment by Rasmusfk** [comment]
So this turned out to be a bit of a rabbit hole. The I2C spec. specifies clock stretching, which the BNO085 uses, but it doesn't specify any upper limit for how long a target device can stretch the clock:
https://learn.adafruit.com/working-with-i2c-devices/clock-stretching

The BNO085 is correctly detected, when increasing the clock stretch timeout from 100us to 500us like this in Wire.cpp:

```
static bool _clockStretch(pin_size_t pin) {
    auto end = time_us_64() + 500; // <-- increased from 100 to 500

    while ((time_us_64() < end) && (!digitalRead(pin))) { /* noop */ }
    return digitalRead(pin);
}
```

There is not anything magic about 500us other that it is the shortest timeout where the BNO085 is still reliably detected. Other I2C devices might need (much?) longer timeouts.

In particular for the BNO085 the increased timeout is only needed when reading the ACK/NACK:


```
...
 if (!_clockStretch(scl)) {
      goto stop;
  }

  ack = digitalRead(sda) == LOW; 
```

Would you accept a pull request where the timeout in _clockStretch() is increased to i.e. 5000 (to be on the safe side)?
The change would have minimal impact on how long ie the i2c_scanner example takes to run.

**Pull request closed without merging**
