### PR TITLE
 Change Cytron Maker UNO RP2040 name to Cytron Maker Uno RP2040 and add board name in the README.md list

### PR DESCRIPTION
**Pull request by noqman**
Good day!

Please help me change the board name from "Cytron Maker UNO RP2040" to "Cytron Maker Uno RP2040". Let me know if I missed something or anything that I need to change. 

Thank you.

### CODE REVIEW

**Comment by earlephilhower** [comment]
You'll need to rebase/merge with current master before we can check this out.  I don't have permissions to do it myself in your PR.

**Review by earlephilhower — CHANGES_REQUESTED** [review]
I just checked the manufacturer site, and it is `UNO` and not `Uno`.  See https://www.cytron.io/p-maker-uno-simplifying-arduino-for-education

**Comment by noqman** [comment]
Thank you for pointing that out. We would like to clarify that 'Maker UNO' was part of our old naming convention.
We'd like to inform you that we have recently standardized our product naming to;

1) all CAPITAL letters (eg. EDU:BIT, REKA:BIT, EDU PICO), or
2) only Capitalize First Letter (eg. Maker Pi Pico, Robo Pico), unless
3) it's part of the acronym/brand like HAT/HAT, pHAT, RP2040 & ESP32 (eg. Maker HAT Base, Maker Uno RP2040)

Therefore, for this product, the updated name is 'Maker Uno RP2040.'"

**Comment by earlephilhower** [comment]
Ah, thanks for the explanation!  LGTM, then.

**Pull request merged**
