### PR TITLE
Add board BridgeTek IDM2040-7A

### PR DESCRIPTION
**Pull request by brtchip-tuannguyen**
For more detail about this board IDM2040-7A, please visit https://brtchip.com/ic-module/product/idm2040-7a/

### CODE REVIEW

**Comment by brtchip-tuannguyen** [comment]
> Can you please remove the additional library you've added? 

I'm done removing it, please have a look to check (commit [b38c78e](https://github.com/earlephilhower/arduino-pico/pull/912/commits/b38c78e4d33e3d72d15b563a46da74917bd5b747)). 

Thank you.

**Review by earlephilhower — APPROVED** [review]
Thanks, LGTM

**Comment by earlephilhower** [comment]
Is this ready to merge?  The PR is listed as "Draft, This pull request is still a work in progress"

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Actually, looks like you need to remove the library directory as well.  Git is now confused and we're still trying to pull in a copy of the library.
image

**Review by earlephilhower — APPROVED** [review]
Looking good now!

**Pull request merged**
