### PR TITLE
Two board variant definitions and a high speed SPI transfer function

### PR DESCRIPTION
**Pull request by ladyada**
For very fast display updates, we have a 'block' transfer SPI function that will send all the data at once without overwriting it with received data, this allows 10x speed up in TFT/OLED display drawing!

### CODE REVIEW

**Comment by ladyada** [comment]
@earlephilhower hihi can you kick the CI or give my account collaborator access so I can get it passing :)

**Comment by earlephilhower** [comment]
Sorry, I think that's something new GH put in to protect against miners.  It should be good to go now for this and any future PRs.  Thx!

**Comment by earlephilhower** [comment]
I haven't added the docs for the new CI checks yet, but other than the pedantic type warning in builds the other issue is the code formatting. check.  You can run `./tests/restyle.sh` to get `SPI.cpp` and its examples to match the astyle guides.

**Comment by ladyada** [comment]
@earlephilhower ok plz give another kick for CI :) should be good now i hope

**Comment by ladyada** [comment]
woo hoo ok ready for review! 😅

**Review by earlephilhower — APPROVED** [review]
Looks good, thanks!  Amazing such a simple change can have such a performance impact.

I'll update the README w/the new boards right after the merge.

**Pull request merged**
